import type { QuoteMode, RecordKind, ServiceStatus } from '@/app/(workspace)/registros/types';
import type { RequestStatus } from '@/app/(workspace)/solicitacoes/types';

export type CatalogStage = {
  serviceTypeId: string;
  label: string;
  resourceId: string;
  estimatedHours: number;
  actualHours?: number | null;
};

export type RealProposal = {
  id: string;
  proposalDate: string;
  company: string;
  requester: string;
  email: string;
  phone: string;
  service: string;
  message: string;
  totalValue: number;
  totalHours?: number;
  quantity?: number;
  batchLabel?: string;
  recordKind: RecordKind;
  serviceTypeId: string;
  partTraitIds: string[];
  resourceIds: string[];
  stages?: CatalogStage[];
  hoursPackageRef?: string;
  equipment?: string;
  assumptions?: string;
  quoteMode?: QuoteMode;
  priceOverrideReason?: string;
  paymentTerms?: string;
  requestStatus: RequestStatus;
  recordStatus?: ServiceStatus;
  hasRecord: boolean;
  actualHours?: number;
  deviationCauseId?: string | null;
  lesson?: string;
  lessonStatus?: 'DRAFT' | 'FORMALIZED';
  scopeChange?: boolean;
  deliveredAt?: string | null;
};

function date(isoDate: string) {
  return `${isoDate}T12:00:00.000Z`;
}

/**
 * Dados fictícios para demonstração.
 *
 * Não representam clientes, pessoas, contatos, contratos,
 * equipamentos ou valores comerciais reais.
 */
export const REAL_PROPOSALS: RealProposal[] = [
  {
    id: 'proposal-01',
    proposalDate: date('2026-01-12'),
    company: 'Indústria Aurora Demo',
    requester: 'Marina Costa',
    email: 'marina.costa@example.com',
    phone: '(00) 90000-0001',
    service: 'Metrologia — pacote demonstrativo',
    message:
      'Pacote fictício de horas para demonstração de serviços de medição, inspeção e engenharia reversa.',
    totalValue: 7200,
    totalHours: 48,
    recordKind: 'single',
    serviceTypeId: 'vocab-4',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13', 'vocab-15', 'vocab-14'],
    hoursPackageRef: 'Pacote Demo — 3 meses',
    equipment: 'CMM DEMO 01 + SCANNER DEMO + CMM DEMO 02',
    assumptions:
      'Pacote fictício para demonstração do consumo de horas e diferentes modalidades de serviço.',
    priceOverrideReason: 'Valor demonstrativo definido para testes.',
    paymentTerms: '3 parcelas mensais',
    requestStatus: 'CONVERTED',
    recordStatus: 'QUOTED',
    hasRecord: true,
  },
  {
    id: 'proposal-02',
    proposalDate: date('2026-01-20'),
    company: 'AeroLab Demo',
    requester: 'Rafael Martins',
    email: 'rafael.martins@example.com',
    phone: '(00) 90000-0002',
    service: 'Escaneamento e engenharia reversa — Projeto Demo',
    message:
      'Escaneamento e engenharia reversa de uma peça fictícia. Entrega de modelo digital para demonstração do fluxo.',
    totalValue: 22800,
    totalHours: 120,
    recordKind: 'composite',
    serviceTypeId: 'vocab-2',
    partTraitIds: ['vocab-22'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      {
        serviceTypeId: 'vocab-1',
        label: 'Escaneamento demonstrativo',
        resourceId: 'vocab-18',
        estimatedHours: 60,
      },
      {
        serviceTypeId: 'vocab-2',
        label: 'Engenharia reversa demonstrativa',
        resourceId: 'vocab-20',
        estimatedHours: 60,
      },
    ],
    equipment: 'SCANNER DEMO + CMM DEMO',
    assumptions: 'Execução dividida em etapas para demonstração do fluxo de engenharia reversa.',
    priceOverrideReason: 'Valor fictício para demonstração.',
    paymentTerms: 'Entrada + parcelas mensais',
    requestStatus: 'CONVERTED',
    recordStatus: 'QUOTED',
    hasRecord: true,
  },
  {
    id: 'proposal-03',
    proposalDate: date('2026-02-03'),
    company: 'HidraTech Demo',
    requester: 'Camila Souza',
    email: 'camila.souza@example.com',
    phone: '(00) 90000-0003',
    service: 'Relatório de análise de falhas',
    message: 'Análise fictícia de falha em componente hidráulico para demonstração.',
    totalValue: 680,
    totalHours: 4,
    recordKind: 'single',
    serviceTypeId: 'vocab-8',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13'],
    stages: [
      {
        serviceTypeId: 'vocab-8',
        label: 'Análise de falhas',
        resourceId: 'vocab-13',
        estimatedHours: 4,
        actualHours: 4,
      },
    ],
    equipment: 'CMM DEMO 01',
    assumptions: 'Laudo fictício utilizado para demonstração do fluxo.',
    priceOverrideReason: 'Valor demonstrativo.',
    paymentTerms: 'Boleto 15 dias',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 4,
    deliveredAt: date('2026-02-10'),
    lesson: 'Documentação técnica adequada pode reduzir o tempo de análise.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-04',
    proposalDate: date('2026-02-17'),
    company: 'Indústria Aurora Demo',
    requester: 'Marina Costa',
    email: 'marina.costa@example.com',
    phone: '(00) 90000-0004',
    service: 'Metrologia — pacote demonstrativo semestral',
    message: 'Pacote fictício de horas com validade de seis meses para demonstração do sistema.',
    totalValue: 14400,
    totalHours: 96,
    recordKind: 'single',
    serviceTypeId: 'vocab-4',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13', 'vocab-15', 'vocab-14'],
    hoursPackageRef: 'Pacote Demo — 6 meses',
    equipment: 'CMM DEMO 01 + SCANNER DEMO + CMM DEMO 02',
    assumptions: 'Pacote fictício para demonstração de diferentes modalidades de análise.',
    priceOverrideReason: 'Contrato demonstrativo.',
    paymentTerms: '6 parcelas mensais',
    requestStatus: 'CONVERTED',
    recordStatus: 'QUOTED',
    hasRecord: true,
  },
  {
    id: 'proposal-05',
    proposalDate: date('2026-02-24'),
    company: 'HidraTech Demo',
    requester: 'Pedro Lima',
    email: 'pedro.lima@example.com',
    phone: '(00) 90000-0005',
    service: 'Análise de falhas — 2 peças',
    message: 'Análise fictícia de falhas em dois componentes para demonstração.',
    totalValue: 920,
    totalHours: 6,
    quantity: 2,
    recordKind: 'batch',
    batchLabel: 'Componentes hidráulicos Demo 1–2',
    serviceTypeId: 'vocab-8',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13'],
    stages: [
      {
        serviceTypeId: 'vocab-8',
        label: 'Análise de falhas',
        resourceId: 'vocab-13',
        estimatedHours: 3,
      },
    ],
    equipment: 'CMM DEMO 01',
    assumptions: 'Dados e componentes utilizados exclusivamente para demonstração.',
    paymentTerms: 'Boleto 15 dias',
    requestStatus: 'ON_GOING',
    recordStatus: 'DRAFT',
    hasRecord: true,
  },
  {
    id: 'proposal-06',
    proposalDate: date('2026-03-03'),
    company: 'RossiTech Demo',
    requester: 'Lucas Mendes',
    email: 'lucas.mendes@example.com',
    phone: '(00) 90000-0006',
    service: 'Escaneamento 3D com análise comparativa CAD',
    message: 'Escaneamento 3D e comparação fictícia entre peça digitalizada e modelo CAD.',
    totalValue: 1800,
    totalHours: 8,
    quantity: 4,
    recordKind: 'batch',
    batchLabel: 'Peças Demo 1–4',
    serviceTypeId: 'vocab-5',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-14', 'vocab-20'],
    stages: [
      {
        serviceTypeId: 'vocab-1',
        label: 'Digitalização 3D',
        resourceId: 'vocab-14',
        estimatedHours: 1,
        actualHours: 1,
      },
      {
        serviceTypeId: 'vocab-5',
        label: 'Comparação CAD × peça',
        resourceId: 'vocab-20',
        estimatedHours: 1,
        actualHours: 1,
      },
    ],
    equipment: 'SCANNER DEMO + CMM DEMO',
    assumptions: 'Modelo CAD fictício utilizado para demonstrar o mapa de tolerâncias.',
    priceOverrideReason: 'Valor demonstrativo por peça.',
    paymentTerms: 'Boleto 30 dias',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 8,
    deliveredAt: date('2026-03-12'),
    lesson: 'O modelo CAD precisa estar disponível na revisão utilizada durante a comparação.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: 'vocab-26',
  },
  {
    id: 'proposal-07',
    proposalDate: date('2026-03-18'),
    company: 'Alimentos Horizonte Demo',
    requester: 'Fernanda Oliveira',
    email: 'fernanda.oliveira@example.com',
    phone: '(00) 90000-0007',
    service: 'Digitalização 3D e engenharia reversa — 10 peças',
    message: 'Digitalização 3D e engenharia reversa de componentes fictícios para demonstração.',
    totalValue: 11200,
    totalHours: 50,
    quantity: 10,
    recordKind: 'batch',
    batchLabel: 'Lote Demo 01',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-22'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      {
        serviceTypeId: 'vocab-1',
        label: 'Digitalização 3D',
        resourceId: 'vocab-18',
        estimatedHours: 3,
      },
      {
        serviceTypeId: 'vocab-2',
        label: 'Engenharia reversa',
        resourceId: 'vocab-20',
        estimatedHours: 2,
      },
    ],
    equipment: 'SCANNER DEMO + CMM DEMO',
    assumptions: 'Execução fictícia utilizada para representar um lote de peças.',
    priceOverrideReason: 'Valor demonstrativo do lote.',
    paymentTerms: 'Parcelamento demonstrativo',
    requestStatus: 'NEW',
    recordStatus: 'QUOTED',
    hasRecord: true,
  },
  {
    id: 'proposal-08',
    proposalDate: date('2026-03-27'),
    company: 'Moldes Prisma Demo',
    requester: 'André Ribeiro',
    email: 'andre.ribeiro@example.com',
    phone: '(00) 90000-0008',
    service: 'Escaneamento 3D — entrega STL',
    message: 'Escaneamento 3D de dois objetos fictícios com entrega de arquivos STL.',
    totalValue: 640,
    totalHours: 2,
    quantity: 2,
    recordKind: 'batch',
    batchLabel: 'Objetos Demo 1–2',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-22'],
    resourceIds: ['vocab-14'],
    stages: [
      {
        serviceTypeId: 'vocab-1',
        label: 'Digitalização 3D',
        resourceId: 'vocab-14',
        estimatedHours: 1,
        actualHours: 1,
      },
    ],
    equipment: 'SCANNER DEMO',
    assumptions: 'Arquivos STL fictícios para demonstração.',
    priceOverrideReason: 'Valor demonstrativo por arquivo.',
    paymentTerms: 'PIX',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 2,
    deliveredAt: date('2026-04-03'),
    lesson: 'Objetos pequenos podem exigir preparação adicional para o registro óptico.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-09',
    proposalDate: date('2026-04-10'),
    company: 'Processos Sigma Demo',
    requester: 'Juliana Ferreira',
    email: 'juliana.ferreira@example.com',
    phone: '(00) 90000-0009',
    service: 'Árvore de equipamentos + análise de falhas',
    message:
      'Projeto fictício de estruturação de equipamentos, organização de dados e análises técnicas.',
    totalValue: 17600,
    totalHours: 120,
    recordKind: 'composite',
    serviceTypeId: 'vocab-9',
    partTraitIds: ['vocab-22'],
    resourceIds: ['vocab-15', 'vocab-14'],
    hoursPackageRef: 'Projeto Demo — 120 h',
    stages: [
      {
        serviceTypeId: 'vocab-9',
        label: 'Árvore de equipamentos',
        resourceId: 'vocab-14',
        estimatedHours: 40,
      },
      {
        serviceTypeId: 'vocab-10',
        label: 'Organização de dados',
        resourceId: 'vocab-20',
        estimatedHours: 40,
      },
      {
        serviceTypeId: 'vocab-12',
        label: 'Treinamento demonstrativo',
        resourceId: 'vocab-13',
        estimatedHours: 4,
      },
      {
        serviceTypeId: 'vocab-8',
        label: 'Análise técnica',
        resourceId: 'vocab-15',
        estimatedHours: 36,
      },
    ],
    equipment: 'CMM DEMO + SCANNER DEMO',
    assumptions: 'Pacote fictício com treinamento e horas técnicas para demonstração.',
    priceOverrideReason: 'Pacote demonstrativo de serviços.',
    paymentTerms: 'Parcelamento demonstrativo',
    requestStatus: 'NEW',
    recordStatus: 'QUOTED',
    hasRecord: true,
  },
  {
    id: 'proposal-10',
    proposalDate: date('2026-04-17'),
    company: 'MotoLab Demo',
    requester: 'Bruno Alves',
    email: 'bruno.alves@example.com',
    phone: '(00) 90000-0010',
    service: 'Scan + engenharia reversa — componentes',
    message: 'Escaneamento 3D e engenharia reversa de dois componentes fictícios.',
    totalValue: 560,
    totalHours: 4,
    quantity: 2,
    recordKind: 'batch',
    batchLabel: 'Componentes Demo 1–2',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-22'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      {
        serviceTypeId: 'vocab-1',
        label: 'Digitalização 3D',
        resourceId: 'vocab-18',
        estimatedHours: 1,
      },
      {
        serviceTypeId: 'vocab-2',
        label: 'Engenharia reversa',
        resourceId: 'vocab-20',
        estimatedHours: 1,
      },
    ],
    equipment: 'SCANNER DEMO + CMM DEMO',
    assumptions: 'Cronograma fictício para demonstração.',
    priceOverrideReason: 'Valor demonstrativo.',
    paymentTerms: 'À vista',
    requestStatus: 'NEW',
    recordStatus: 'DRAFT',
    hasRecord: true,
  },
  {
    id: 'proposal-11',
    proposalDate: date('2026-04-24'),
    company: 'AeroParts Demo',
    requester: 'Marcos Silva',
    email: 'marcos.silva@example.com',
    phone: '(00) 90000-0011',
    service: 'Inspeção dimensional — lote Demo',
    message: 'Inspeção geométrica e dimensional de quatro componentes fictícios.',
    totalValue: 2680,
    totalHours: 8,
    quantity: 4,
    batchLabel: 'Lote Aero Demo 01',
    recordKind: 'batch',
    serviceTypeId: 'vocab-4',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13'],
    stages: [
      {
        serviceTypeId: 'vocab-4',
        label: 'Inspeção dimensional',
        resourceId: 'vocab-13',
        estimatedHours: 2,
        actualHours: 2,
      },
    ],
    equipment: 'CMM DEMO 01',
    assumptions: 'Relatório dimensional fictício utilizado para demonstração.',
    priceOverrideReason: 'Valor demonstrativo por componente.',
    paymentTerms: 'Boleto 30 dias',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 8,
    deliveredAt: date('2026-05-04'),
    lesson: 'Componentes semelhantes podem compartilhar etapas do programa de medição.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-12',
    proposalDate: date('2026-04-24'),
    company: 'AeroParts Demo',
    requester: 'Marcos Silva',
    email: 'marcos.silva@example.com',
    phone: '(00) 90000-0012',
    service: 'Inspeção dimensional — segundo lote Demo',
    message: 'Inspeção dimensional de quatro peças fictícias para demonstração de um segundo lote.',
    totalValue: 2680,
    totalHours: 8,
    quantity: 4,
    batchLabel: 'Lote Aero Demo 02',
    recordKind: 'batch',
    serviceTypeId: 'vocab-4',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13'],
    stages: [
      {
        serviceTypeId: 'vocab-4',
        label: 'Inspeção dimensional',
        resourceId: 'vocab-13',
        estimatedHours: 2,
        actualHours: 2,
      },
    ],
    equipment: 'CMM DEMO 01',
    assumptions: 'Relatório dimensional fictício e prazo demonstrativo.',
    priceOverrideReason: 'Valor demonstrativo por componente.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 8,
    deliveredAt: date('2026-05-06'),
    lesson: 'A reutilização de programas pode reduzir a preparação de lotes semelhantes.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-13',
    proposalDate: date('2026-05-01'),
    company: 'AutoLab Demo',
    requester: 'Ricardo Santos',
    email: 'ricardo.santos@example.com',
    phone: '(00) 90000-0013',
    service: 'Metrologia — componente Demo',
    message: 'Inspeção geométrica e dimensional de um componente fictício.',
    totalValue: 280,
    totalHours: 2,
    recordKind: 'single',
    serviceTypeId: 'vocab-4',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13'],
    stages: [
      {
        serviceTypeId: 'vocab-4',
        label: 'Inspeção dimensional',
        resourceId: 'vocab-13',
        estimatedHours: 2,
        actualHours: 2,
      },
    ],
    equipment: 'CMM DEMO 01',
    assumptions: 'Componente fictício utilizado exclusivamente para demonstração.',
    priceOverrideReason: 'Valor demonstrativo.',
    paymentTerms: '30 dias',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 2,
    deliveredAt: date('2026-05-08'),
    lessonStatus: 'FORMALIZED',
    lesson: 'Componente de pequeno porte com fixação simples.',
    deviationCauseId: null,
  },
  {
    id: 'proposal-14',
    proposalDate: date('2026-05-08'),
    company: 'ImagemLab Demo',
    requester: 'Sérgio Martins',
    email: 'sergio.martins@example.com',
    phone: '(00) 90000-0014',
    service: 'Scan + engenharia reversa — peça Demo',
    message: 'Escaneamento 3D e engenharia reversa de uma peça fictícia.',
    totalValue: 440,
    totalHours: 4,
    recordKind: 'single',
    batchLabel: 'Peça Demo 01',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-22'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      {
        serviceTypeId: 'vocab-1',
        label: 'Digitalização 3D',
        resourceId: 'vocab-18',
        estimatedHours: 2,
        actualHours: 2,
      },
      {
        serviceTypeId: 'vocab-2',
        label: 'Engenharia reversa',
        resourceId: 'vocab-20',
        estimatedHours: 2,
        actualHours: 2,
      },
    ],
    equipment: 'SCANNER DEMO + CMM DEMO',
    assumptions: 'Prazo fictício de sete dias úteis para demonstração.',
    priceOverrideReason: 'Valor demonstrativo.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 4,
    deliveredAt: date('2026-05-16'),
    lessonStatus: 'FORMALIZED',
    lesson: 'Modelo digital validado em uma única revisão.',
    deviationCauseId: null,
  },
  {
    id: 'proposal-15',
    proposalDate: date('2026-05-12'),
    company: 'Componentes Delta Demo',
    requester: 'Humberto Martins',
    email: 'humberto.martins@example.com',
    phone: '(00) 90000-0015',
    service: 'Scan + engenharia reversa — peça Demo',
    message: 'Escaneamento 3D e engenharia reversa de uma peça fictícia.',
    totalValue: 620,
    totalHours: 4,
    recordKind: 'single',
    batchLabel: 'Peça Demo 02',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-22'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      {
        serviceTypeId: 'vocab-1',
        label: 'Digitalização 3D',
        resourceId: 'vocab-18',
        estimatedHours: 2,
        actualHours: 2,
      },
      {
        serviceTypeId: 'vocab-2',
        label: 'Engenharia reversa',
        resourceId: 'vocab-20',
        estimatedHours: 2,
        actualHours: 2,
      },
    ],
    equipment: 'SCANNER DEMO + CMM DEMO',
    assumptions: 'Contato e dados fictícios para demonstração.',
    priceOverrideReason: 'Valor demonstrativo.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 4,
    deliveredAt: date('2026-05-20'),
    lessonStatus: 'FORMALIZED',
    lesson: 'Peça única com geometria adequada para digitalização rápida.',
    deviationCauseId: null,
  },
  {
    id: 'proposal-16',
    proposalDate: date('2026-05-21'),
    company: 'EcoProcess Demo',
    requester: 'Italo Mendes',
    email: 'italo.mendes@example.com',
    phone: '(00) 90000-0016',
    service: 'Redesign + digitalização mensal',
    message: 'Redesign de quatro peças fictícias e pacote mensal de digitalização.',
    totalValue: 12400,
    totalHours: 80,
    recordKind: 'composite',
    serviceTypeId: 'vocab-9',
    partTraitIds: ['vocab-22'],
    resourceIds: ['vocab-18', 'vocab-20'],
    hoursPackageRef: 'Pacote Demo — 70 h de digitalização',
    stages: [
      {
        serviceTypeId: 'vocab-2',
        label: 'Redesign de peças',
        resourceId: 'vocab-20',
        estimatedHours: 14,
      },
      {
        serviceTypeId: 'vocab-9',
        label: 'Árvore de equipamentos',
        resourceId: 'vocab-18',
        estimatedHours: 8,
      },
      {
        serviceTypeId: 'vocab-1',
        label: 'Digitalização mensal',
        resourceId: 'vocab-18',
        estimatedHours: 58,
      },
    ],
    equipment: 'SCANNER DEMO + CMM DEMO',
    assumptions: 'Projeto fictício com execução distribuída ao longo de vários meses.',
    priceOverrideReason: 'Pacote demonstrativo de serviços.',
    paymentTerms: 'Parcelamento mensal',
    requestStatus: 'CONVERTED',
    recordStatus: 'QUOTED',
    hasRecord: true,
  },
  {
    id: 'proposal-17',
    proposalDate: date('2026-05-27'),
    company: 'CBBR Demo',
    requester: 'Gabriel Viana',
    email: 'gabriel.viana@example.com',
    phone: '(00) 90000-0017',
    service: 'Scan + engenharia reversa — 6 peças',
    message: 'Escaneamento 3D e engenharia reversa de seis componentes fictícios.',
    totalValue: 460,
    totalHours: 4,
    quantity: 6,
    recordKind: 'batch',
    batchLabel: 'Lote Demo 1–6',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-22'],
    resourceIds: ['vocab-14', 'vocab-20'],
    stages: [
      {
        serviceTypeId: 'vocab-1',
        label: 'Digitalização 3D',
        resourceId: 'vocab-14',
        estimatedHours: 2,
        actualHours: 2,
      },
      {
        serviceTypeId: 'vocab-2',
        label: 'Engenharia reversa',
        resourceId: 'vocab-20',
        estimatedHours: 2,
        actualHours: 2,
      },
    ],
    equipment: 'SCANNER DEMO + CMM DEMO',
    assumptions: 'Lote fictício com desconto demonstrativo para o primeiro serviço.',
    priceOverrideReason: 'Desconto demonstrativo.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 4,
    deliveredAt: date('2026-06-05'),
    lesson: 'Peças similares permitem reaproveitamento de configuração de digitalização.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-18',
    proposalDate: date('2026-06-15'),
    company: 'Componentes Delta Demo',
    requester: 'Humberto Martins',
    email: 'humberto.martins@example.com',
    phone: '(00) 90000-0018',
    service: 'Scan + engenharia reversa — 4 peças',
    message: 'Digitalização e engenharia reversa de quatro peças fictícias.',
    totalValue: 1380,
    totalHours: 9,
    quantity: 4,
    recordKind: 'batch',
    batchLabel: 'Peças Demo 1–4',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-22'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      {
        serviceTypeId: 'vocab-1',
        label: 'Digitalização 3D',
        resourceId: 'vocab-18',
        estimatedHours: 5,
        actualHours: 5,
      },
      {
        serviceTypeId: 'vocab-2',
        label: 'Engenharia reversa',
        resourceId: 'vocab-20',
        estimatedHours: 4,
        actualHours: 4,
      },
    ],
    equipment: 'SCANNER DEMO + CMM DEMO',
    assumptions: 'Condição de pagamento fictícia.',
    priceOverrideReason: 'Valor demonstrativo do lote.',
    paymentTerms: 'Boleto 30 dias',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 9,
    deliveredAt: date('2026-06-28'),
    lessonStatus: 'FORMALIZED',
    lesson: 'Uma das peças exigiu mais tempo de modelagem que as demais.',
    deviationCauseId: 'vocab-26',
  },
  {
    id: 'proposal-19',
    proposalDate: date('2026-06-23'),
    company: 'Componentes Delta Demo',
    requester: 'Humberto Martins',
    email: 'humberto.martins@example.com',
    phone: '(00) 90000-0019',
    service: 'Scan + engenharia reversa — componentes simétricos',
    message: 'Escaneamento e engenharia reversa de dois componentes fictícios.',
    totalValue: 920,
    totalHours: 6,
    quantity: 2,
    recordKind: 'batch',
    batchLabel: 'Componentes Demo A/B',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      {
        serviceTypeId: 'vocab-1',
        label: 'Digitalização 3D',
        resourceId: 'vocab-18',
        estimatedHours: 3,
        actualHours: 3,
      },
      {
        serviceTypeId: 'vocab-2',
        label: 'Engenharia reversa',
        resourceId: 'vocab-20',
        estimatedHours: 3,
        actualHours: 3,
      },
    ],
    equipment: 'SCANNER DEMO + CMM DEMO',
    assumptions: 'Prazo demonstrativo de 45 dias.',
    priceOverrideReason: 'Valor fictício para demonstração.',
    paymentTerms: 'Boleto 45 dias',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 6,
    deliveredAt: date('2026-07-05'),
    lessonStatus: 'FORMALIZED',
    lesson: 'Componentes simétricos permitem reaproveitamento parcial do modelo.',
    deviationCauseId: null,
  },
  {
    id: 'proposal-20',
    proposalDate: date('2026-06-24'),
    company: 'Sameq Demo',
    requester: 'Samantha Oliveira',
    email: 'samantha.oliveira@example.com',
    phone: '(00) 90000-0020',
    service: 'Scan + engenharia reversa — 3 peças',
    message: 'Digitalização e engenharia reversa de três componentes fictícios.',
    totalValue: 430,
    totalHours: 3,
    quantity: 3,
    recordKind: 'batch',
    batchLabel: 'Lote Demo 3 peças',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-14', 'vocab-20'],
    stages: [
      {
        serviceTypeId: 'vocab-1',
        label: 'Digitalização 3D',
        resourceId: 'vocab-14',
        estimatedHours: 1,
        actualHours: 1,
      },
      {
        serviceTypeId: 'vocab-2',
        label: 'Engenharia reversa',
        resourceId: 'vocab-20',
        estimatedHours: 2,
        actualHours: 2,
      },
    ],
    equipment: 'SCANNER DEMO + CMM DEMO',
    assumptions: 'Dados de contato e condições comerciais são fictícios.',
    priceOverrideReason: 'Valor demonstrativo.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 3,
    deliveredAt: date('2026-07-02'),
    lesson: 'Peças com tolerância apertada podem exigir pontos adicionais de referência.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: 'vocab-26',
  },
  {
    id: 'proposal-21',
    proposalDate: date('2026-06-24'),
    company: 'Cargill Demo',
    requester: 'Lucas Oliveira',
    email: 'lucas.oliveira@example.com',
    phone: '(00) 90000-0021',
    service: 'Pacote anual de horas técnicas',
    message:
      'Pacote fictício de horas técnicas para demonstração de diferentes serviços metrológicos.',
    totalValue: 16000,
    totalHours: 120,
    recordKind: 'single',
    serviceTypeId: 'vocab-4',
    partTraitIds: ['vocab-22'],
    resourceIds: ['vocab-13', 'vocab-14', 'vocab-15'],
    hoursPackageRef: 'Pacote Demo Anual — 120 h',
    equipment: 'Multirecurso Demo',
    assumptions: 'Hora técnica e condições comerciais são fictícias.',
    priceOverrideReason: 'Pacote demonstrativo de 120 horas.',
    paymentTerms: 'Boleto 60 dias',
    requestStatus: 'CONVERTED',
    recordStatus: 'QUOTED',
    hasRecord: true,
  },
  {
    id: 'proposal-22',
    proposalDate: date('2026-06-24'),
    company: 'Fiberglass Demo',
    requester: 'José Martins',
    email: 'jose.martins@example.com',
    phone: '(00) 90000-0022',
    service: 'Consultoria técnica — projeto Demo',
    message:
      'Consultoria técnica e organizacional fictícia para demonstração do módulo de gestão do conhecimento.',
    totalValue: 17600,
    totalHours: 120,
    recordKind: 'single',
    serviceTypeId: 'vocab-11',
    partTraitIds: [],
    resourceIds: [],
    hoursPackageRef: 'Consultoria Demo — 120 h',
    assumptions: 'Projeto totalmente fictício utilizado para demonstração de consultoria.',
    priceOverrideReason: 'Valor demonstrativo.',
    paymentTerms: '4 parcelas mensais',
    requestStatus: 'NEW',
    hasRecord: false,
  },
  {
    id: 'proposal-23',
    proposalDate: date('2026-06-30'),
    company: 'AeroParts Demo',
    requester: 'Marcos Silva',
    email: 'marcos.silva@example.com',
    phone: '(00) 90000-0023',
    service: 'Inspeção dimensional — 5 componentes',
    message: 'Inspeção geométrica e dimensional de cinco componentes fictícios.',
    totalValue: 3150,
    totalHours: 10,
    quantity: 5,
    batchLabel: 'Lote Aero Demo 03',
    recordKind: 'batch',
    serviceTypeId: 'vocab-4',
    partTraitIds: ['vocab-23', 'vocab-22'],
    resourceIds: ['vocab-13'],
    stages: [
      {
        serviceTypeId: 'vocab-4',
        label: 'Inspeção dimensional',
        resourceId: 'vocab-13',
        estimatedHours: 2,
        actualHours: 2.2,
      },
    ],
    equipment: 'CMM DEMO 01',
    assumptions: 'Componentes e números de identificação são fictícios.',
    priceOverrideReason: 'Valor demonstrativo.',
    paymentTerms: 'Boleto 60 dias',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 11,
    deliveredAt: date('2026-07-15'),
    scopeChange: true,
    lesson: 'Fixações mais complexas podem aumentar o tempo de preparação.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: 'vocab-25',
  },
  {
    id: 'proposal-24',
    proposalDate: date('2026-07-10'),
    company: 'Vertical Demo',
    requester: 'Cleber Ribeiro',
    email: 'cleber.ribeiro@example.com',
    phone: '(00) 90000-0024',
    service: 'Inspeção dimensional — 2 componentes',
    message: 'Avaliação dimensional de dois componentes fictícios.',
    totalValue: 780,
    totalHours: 5,
    quantity: 2,
    batchLabel: 'Componentes Demo 1–2',
    recordKind: 'batch',
    serviceTypeId: 'vocab-4',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13'],
    stages: [
      {
        serviceTypeId: 'vocab-4',
        label: 'Inspeção dimensional',
        resourceId: 'vocab-13',
        estimatedHours: 2.5,
        actualHours: 2.5,
      },
    ],
    equipment: 'CMM DEMO 01',
    assumptions: 'Laboratório e condições de execução são fictícios.',
    priceOverrideReason: 'Valor demonstrativo.',
    paymentTerms: 'Condição demonstrativa',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 5,
    deliveredAt: date('2026-07-18'),
    lesson: 'Programa de medição pode ser reutilizado entre componentes semelhantes.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-25',
    proposalDate: date('2026-07-28'),
    company: 'Componentes Delta Demo',
    requester: 'Humberto Martins',
    email: 'humberto.martins@example.com',
    phone: '(00) 90000-0025',
    service: 'Scan + eng. reversa — dois componentes',
    message: 'Escaneamento 3D e engenharia reversa de dois componentes fictícios.',
    totalValue: 2280,
    totalHours: 16,
    quantity: 2,
    recordKind: 'batch',
    batchLabel: 'Componentes Demo 04–05',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      {
        serviceTypeId: 'vocab-1',
        label: 'Digitalização 3D — componente A',
        resourceId: 'vocab-18',
        estimatedHours: 6,
      },
      {
        serviceTypeId: 'vocab-2',
        label: 'Engenharia reversa — componente B',
        resourceId: 'vocab-20',
        estimatedHours: 10,
      },
    ],
    equipment: 'SCANNER DEMO + CMM DEMO',
    assumptions: 'Dados, contatos e condições comerciais são fictícios.',
    priceOverrideReason: 'Valor demonstrativo.',
    paymentTerms: 'Boleto 60 dias',
    requestStatus: 'NEW',
    recordStatus: 'DRAFT',
    hasRecord: true,
  },
  {
    id: 'proposal-26',
    proposalDate: date('2026-07-30'),
    company: 'Componentes Delta Demo',
    requester: 'Gilberto Martins',
    email: 'gilberto.martins@example.com',
    phone: '(00) 90200-0025',
    service: 'Scan + eng. reversa — dois componentes',
    message: 'Escaneamento 3D e engenharia reversa de dois componentes fictícios.',
    totalValue: 2280,
    totalHours: 16,
    quantity: 2,
    recordKind: 'batch',
    batchLabel: 'Componentes Demo 04–05',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      {
        serviceTypeId: 'vocab-1',
        label: 'Digitalização 3D — componente A',
        resourceId: 'vocab-18',
        estimatedHours: 6,
      },
      {
        serviceTypeId: 'vocab-2',
        label: 'Engenharia reversa — componente B',
        resourceId: 'vocab-20',
        estimatedHours: 10,
      },
    ],
    equipment: 'SCANNER DEMO + CMM DEMO',
    assumptions: 'Dados, contatos e condições comerciais são fictícios.',
    priceOverrideReason: 'Valor demonstrativo.',
    paymentTerms: 'Boleto 60 dias',
    requestStatus: 'NEW',
    recordStatus: 'DRAFT',
    hasRecord: true,
  },
  {
    id: 'proposal-27',
    proposalDate: date('2026-08-05'),
    company: 'Prisma Scan Demo',
    requester: 'Ana Duarte',
    email: 'ana.duarte@example.com',
    phone: '(00) 90000-0027',
    service: 'Scan + eng. reversa — lote tolerância apertada',
    message: 'Lote fictício para enriquecer histórico do assistente com tolerância apertada.',
    totalValue: 840,
    totalHours: 6,
    quantity: 2,
    recordKind: 'batch',
    batchLabel: 'Mock lote TA 01',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-14', 'vocab-20'],
    stages: [
      { serviceTypeId: 'vocab-1', label: 'Digitalização 3D', resourceId: 'vocab-14', estimatedHours: 2, actualHours: 2.5 },
      { serviceTypeId: 'vocab-2', label: 'Engenharia reversa', resourceId: 'vocab-20', estimatedHours: 1, actualHours: 1 },
    ],
    assumptions: 'Dado mock — valores e prazos não representam contratos reais.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 7,
    deliveredAt: date('2026-08-12'),
    lesson: 'Tolerância apertada exige mais pontos de referência na digitalização.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: 'vocab-26',
  },
  {
    id: 'proposal-28',
    proposalDate: date('2026-08-08'),
    company: 'Prisma Scan Demo',
    requester: 'Ana Duarte',
    email: 'ana.duarte@example.com',
    phone: '(00) 90000-0028',
    service: 'Scan + eng. reversa — 3 peças TA',
    message: 'Segundo lote mock com mesma classificação para histórico comparável.',
    totalValue: 1290,
    totalHours: 9,
    quantity: 3,
    recordKind: 'batch',
    batchLabel: 'Mock lote TA 02',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      { serviceTypeId: 'vocab-1', label: 'Digitalização 3D', resourceId: 'vocab-18', estimatedHours: 2, actualHours: 2 },
      { serviceTypeId: 'vocab-2', label: 'Engenharia reversa', resourceId: 'vocab-20', estimatedHours: 1, actualHours: 1.2 },
    ],
    assumptions: 'Mock catalog — empresa e contatos fictícios.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 9.6,
    deliveredAt: date('2026-08-16'),
    lesson: 'Lotes pequenos com peças similares permitem reaproveitar malha base.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-29',
    proposalDate: date('2026-08-12'),
    company: 'Titan Metrology Demo',
    requester: 'Paulo Nunes',
    email: 'paulo.nunes@example.com',
    phone: '(00) 90000-0029',
    service: 'Inspeção dimensional — lote TA mock',
    message: 'Histórico mock de metrologia com tolerância apertada.',
    totalValue: 1950,
    totalHours: 10,
    quantity: 5,
    recordKind: 'batch',
    batchLabel: 'Mock CMM TA 01',
    serviceTypeId: 'vocab-4',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13'],
    stages: [
      { serviceTypeId: 'vocab-4', label: 'Inspeção dimensional', resourceId: 'vocab-13', estimatedHours: 2, actualHours: 2.1 },
    ],
    assumptions: 'Dados mock para demonstração de faixa mediana de preços.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 10.5,
    deliveredAt: date('2026-08-20'),
    lesson: 'Programas reutilizados reduzem tempo de setup em lotes TA.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-30',
    proposalDate: date('2026-08-15'),
    company: 'Titan Metrology Demo',
    requester: 'Paulo Nunes',
    email: 'paulo.nunes@example.com',
    phone: '(00) 90000-0030',
    service: 'Inspeção dimensional — lote TA mock 2',
    message: 'Mais um caso mock de inspeção dimensional.',
    totalValue: 2100,
    totalHours: 12,
    quantity: 6,
    recordKind: 'batch',
    batchLabel: 'Mock CMM TA 02',
    serviceTypeId: 'vocab-4',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13'],
    stages: [
      { serviceTypeId: 'vocab-4', label: 'Inspeção dimensional', resourceId: 'vocab-13', estimatedHours: 2, actualHours: 2.4 },
    ],
    assumptions: 'Mock — valores comerciais fictícios.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 14.4,
    deliveredAt: date('2026-08-23'),
    lesson: 'Fixação dedicada compensa o tempo extra em tolerâncias apertadas.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: 'vocab-25',
  },
  {
    id: 'proposal-31',
    proposalDate: date('2026-08-18'),
    company: 'ScanLab Demo',
    requester: 'Renata Pires',
    email: 'renata.pires@example.com',
    phone: '(00) 90000-0031',
    service: 'Digitalização 3D — peça TA mock',
    message: 'Caso unitário mock para histórico de digitalização.',
    totalValue: 520,
    totalHours: 4,
    recordKind: 'single',
    batchLabel: 'Mock peça TA 03',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-14', 'vocab-20'],
    stages: [
      { serviceTypeId: 'vocab-1', label: 'Digitalização 3D', resourceId: 'vocab-14', estimatedHours: 2, actualHours: 2.2 },
      { serviceTypeId: 'vocab-2', label: 'Engenharia reversa', resourceId: 'vocab-20', estimatedHours: 2, actualHours: 2 },
    ],
    assumptions: 'Registro mock versionado no catálogo demo.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 4.2,
    deliveredAt: date('2026-08-25'),
    lesson: 'Peça única TA: validar datum antes de iniciar scan.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: 'vocab-26',
  },
  {
    id: 'proposal-32',
    proposalDate: date('2026-08-22'),
    company: 'ScanLab Demo',
    requester: 'Renata Pires',
    email: 'renata.pires@example.com',
    phone: '(00) 90000-0032',
    service: 'Digitalização 3D — lote TA mock 4',
    message: 'Quarto lote mock com perfil semelhante.',
    totalValue: 760,
    totalHours: 5,
    quantity: 2,
    recordKind: 'batch',
    batchLabel: 'Mock lote TA 04',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      { serviceTypeId: 'vocab-1', label: 'Digitalização 3D', resourceId: 'vocab-18', estimatedHours: 2, actualHours: 1.8 },
      { serviceTypeId: 'vocab-2', label: 'Engenharia reversa', resourceId: 'vocab-20', estimatedHours: 1, actualHours: 1 },
    ],
    assumptions: 'Mock catalog entry.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 5.6,
    deliveredAt: date('2026-08-29'),
    lesson: 'Scanner portátil acelerou digitalização de peça compacta.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-33',
    proposalDate: date('2026-08-26'),
    company: 'HidraTech Demo',
    requester: 'Camila Souza',
    email: 'camila.souza@example.com',
    phone: '(00) 90000-0033',
    service: 'Análise de falhas — componente TA mock',
    message: 'Caso mock de análise de falhas para histórico do assistente.',
    totalValue: 720,
    totalHours: 5,
    recordKind: 'single',
    serviceTypeId: 'vocab-8',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13'],
    stages: [
      { serviceTypeId: 'vocab-8', label: 'Análise de falhas', resourceId: 'vocab-13', estimatedHours: 5, actualHours: 5.5 },
    ],
    assumptions: 'Laudo e componente fictícios.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 5.5,
    deliveredAt: date('2026-09-02'),
    lesson: 'Documentação fotográfica inicial reduz retrabalho na análise.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-34',
    proposalDate: date('2026-08-28'),
    company: 'HidraTech Demo',
    requester: 'Pedro Lima',
    email: 'pedro.lima@example.com',
    phone: '(00) 90000-0034',
    service: 'Análise de falhas — 2 peças TA mock',
    message: 'Segundo caso mock de falhas com tolerância apertada.',
    totalValue: 980,
    totalHours: 7,
    quantity: 2,
    recordKind: 'batch',
    batchLabel: 'Mock falhas TA 01',
    serviceTypeId: 'vocab-8',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13'],
    stages: [
      { serviceTypeId: 'vocab-8', label: 'Análise de falhas', resourceId: 'vocab-13', estimatedHours: 3, actualHours: 3.5 },
    ],
    assumptions: 'Mock — sem vínculo com clientes reais.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 7,
    deliveredAt: date('2026-09-05'),
    lesson: 'Duas peças com falha semelhante compartilham protocolo de corte.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: 'vocab-26',
  },
  {
    id: 'proposal-35',
    proposalDate: date('2026-09-01'),
    company: 'OptiScan Demo',
    requester: 'Felipe Araujo',
    email: 'felipe.araujo@example.com',
    phone: '(00) 90000-0035',
    service: 'Scan + eng. reversa — lote TA mock 5',
    message: 'Quinto lote mock para série de digitalização TA.',
    totalValue: 1120,
    totalHours: 8,
    quantity: 4,
    recordKind: 'batch',
    batchLabel: 'Mock lote TA 05',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-14', 'vocab-20'],
    stages: [
      { serviceTypeId: 'vocab-1', label: 'Digitalização 3D', resourceId: 'vocab-14', estimatedHours: 1.5, actualHours: 1.5 },
      { serviceTypeId: 'vocab-2', label: 'Engenharia reversa', resourceId: 'vocab-20', estimatedHours: 0.5, actualHours: 0.6 },
    ],
    assumptions: 'Entrada mock do catálogo de propostas demo.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 8.4,
    deliveredAt: date('2026-09-08'),
    lesson: 'Malha simplificada suficiente quando cliente só precisa de envelope.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-36',
    proposalDate: date('2026-09-04'),
    company: 'OptiScan Demo',
    requester: 'Felipe Araujo',
    email: 'felipe.araujo@example.com',
    phone: '(00) 90000-0036',
    service: 'Scan + eng. reversa — lote TA mock 6',
    message: 'Sexto lote mock — reforço de histórico 5–14 casos.',
    totalValue: 990,
    totalHours: 7,
    quantity: 3,
    recordKind: 'batch',
    batchLabel: 'Mock lote TA 06',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      { serviceTypeId: 'vocab-1', label: 'Digitalização 3D', resourceId: 'vocab-18', estimatedHours: 1.5, actualHours: 1.7 },
      { serviceTypeId: 'vocab-2', label: 'Engenharia reversa', resourceId: 'vocab-20', estimatedHours: 1, actualHours: 1.1 },
    ],
    assumptions: 'Mock catalog.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 8.4,
    deliveredAt: date('2026-09-11'),
    lesson: 'Engenharia reversa parcial atende quando só faces críticas importam.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-37',
    proposalDate: date('2026-09-07'),
    company: 'MetroZeiss Demo',
    requester: 'Carla Mendes',
    email: 'carla.mendes@example.com',
    phone: '(00) 90000-0037',
    service: 'Inspeção dimensional — lote TA mock 3',
    message: 'Terceiro lote mock de metrologia TA.',
    totalValue: 1680,
    totalHours: 8,
    quantity: 4,
    recordKind: 'batch',
    batchLabel: 'Mock CMM TA 03',
    serviceTypeId: 'vocab-4',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13'],
    stages: [
      { serviceTypeId: 'vocab-4', label: 'Inspeção dimensional', resourceId: 'vocab-13', estimatedHours: 2, actualHours: 2.3 },
    ],
    assumptions: 'Dado mock para painel de indicadores e assistente.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 9.2,
    deliveredAt: date('2026-09-14'),
    lesson: 'Relatório dimensional padronizado acelera entrega em lotes TA.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-38',
    proposalDate: date('2026-09-10'),
    company: 'ScanLab Demo',
    requester: 'Renata Pires',
    email: 'renata.pires@example.com',
    phone: '(00) 90000-0038',
    service: 'Scan + eng. reversa — superfície livre mock',
    message: 'Mock com superfície livre para variar histórico de digitalização.',
    totalValue: 680,
    totalHours: 5,
    recordKind: 'single',
    batchLabel: 'Mock SF 01',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-22'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      { serviceTypeId: 'vocab-1', label: 'Digitalização 3D', resourceId: 'vocab-18', estimatedHours: 3, actualHours: 3.5 },
      { serviceTypeId: 'vocab-2', label: 'Engenharia reversa', resourceId: 'vocab-20', estimatedHours: 2, actualHours: 2.5 },
    ],
    assumptions: 'Mock — geometria complexa fictícia.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 6,
    deliveredAt: date('2026-09-17'),
    lesson: 'Superfícies livres pedem mais tempo de pós-processamento de malha.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: 'vocab-26',
  },
  {
    id: 'proposal-39',
    proposalDate: date('2026-09-12'),
    company: 'ScanLab Demo',
    requester: 'Renata Pires',
    email: 'renata.pires@example.com',
    phone: '(00) 90000-0039',
    service: 'Scan + eng. reversa — lote TA mock 7',
    message: 'Sétimo lote mock TA — reforço para confiança alta.',
    totalValue: 1430,
    totalHours: 10,
    quantity: 2,
    recordKind: 'batch',
    batchLabel: 'Mock lote TA 07',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-14', 'vocab-20'],
    stages: [
      { serviceTypeId: 'vocab-1', label: 'Digitalização 3D', resourceId: 'vocab-14', estimatedHours: 3, actualHours: 3.2 },
      { serviceTypeId: 'vocab-2', label: 'Engenharia reversa', resourceId: 'vocab-20', estimatedHours: 2, actualHours: 2.3 },
    ],
    assumptions: 'Mock catalog — não usar em proposta comercial real.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 11,
    deliveredAt: date('2026-09-19'),
    lesson: 'Dois componentes TA no mesmo lote: sequenciar por complexidade decrescente.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: 'vocab-26',
  },
  {
    id: 'proposal-40',
    proposalDate: date('2026-09-14'),
    company: 'Prisma Scan Demo',
    requester: 'Ana Duarte',
    email: 'ana.duarte@example.com',
    phone: '(00) 90000-0040',
    service: 'Scan + eng. reversa — lote TA mock 8',
    message: 'Oitavo lote mock para série TA.',
    totalValue: 870,
    totalHours: 6,
    quantity: 3,
    recordKind: 'batch',
    batchLabel: 'Mock lote TA 08',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      { serviceTypeId: 'vocab-1', label: 'Digitalização 3D', resourceId: 'vocab-18', estimatedHours: 1.5, actualHours: 1.6 },
      { serviceTypeId: 'vocab-2', label: 'Engenharia reversa', resourceId: 'vocab-20', estimatedHours: 0.5, actualHours: 0.5 },
    ],
    assumptions: 'Mock seed data.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 6.3,
    deliveredAt: date('2026-09-21'),
    lesson: 'Três peças idênticas: digitalizar uma e replicar por simetria quando aplicável.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-41',
    proposalDate: date('2026-09-16'),
    company: 'Prisma Scan Demo',
    requester: 'Ana Duarte',
    email: 'ana.duarte@example.com',
    phone: '(00) 90000-0041',
    service: 'Scan + eng. reversa — lote TA mock 9',
    message: 'Nono lote mock TA.',
    totalValue: 1050,
    totalHours: 7,
    quantity: 2,
    recordKind: 'batch',
    batchLabel: 'Mock lote TA 09',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-14', 'vocab-20'],
    stages: [
      { serviceTypeId: 'vocab-1', label: 'Digitalização 3D', resourceId: 'vocab-14', estimatedHours: 2.5, actualHours: 2.8 },
      { serviceTypeId: 'vocab-2', label: 'Engenharia reversa', resourceId: 'vocab-20', estimatedHours: 1, actualHours: 1.2 },
    ],
    assumptions: 'Mock catalog entry for assistant testing.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 8,
    deliveredAt: date('2026-09-23'),
    lesson: 'Confirmar escopo de entrega CAD antes de modelagem detalhada.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-42',
    proposalDate: date('2026-09-18'),
    company: 'OptiScan Demo',
    requester: 'Felipe Araujo',
    email: 'felipe.araujo@example.com',
    phone: '(00) 90000-0042',
    service: 'Scan + eng. reversa — lote TA mock 10',
    message: 'Décimo lote mock — completar faixa de confiança alta.',
    totalValue: 1180,
    totalHours: 8,
    quantity: 4,
    recordKind: 'batch',
    batchLabel: 'Mock lote TA 10',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-18', 'vocab-20'],
    stages: [
      { serviceTypeId: 'vocab-1', label: 'Digitalização 3D', resourceId: 'vocab-18', estimatedHours: 1.5, actualHours: 1.4 },
      { serviceTypeId: 'vocab-2', label: 'Engenharia reversa', resourceId: 'vocab-20', estimatedHours: 0.5, actualHours: 0.55 },
    ],
    assumptions: 'Mock — base demo versionada.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 7.8,
    deliveredAt: date('2026-09-25'),
    lesson: 'Lote de quatro peças TA: agrupar por fixture comum.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-43',
    proposalDate: date('2026-09-20'),
    company: 'MetroZeiss Demo',
    requester: 'Carla Mendes',
    email: 'carla.mendes@example.com',
    phone: '(00) 90000-0043',
    service: 'Inspeção dimensional — lote TA mock 4',
    message: 'Quarto lote mock metrologia.',
    totalValue: 1540,
    totalHours: 9,
    quantity: 4,
    recordKind: 'batch',
    batchLabel: 'Mock CMM TA 04',
    serviceTypeId: 'vocab-4',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13'],
    stages: [
      { serviceTypeId: 'vocab-4', label: 'Inspeção dimensional', resourceId: 'vocab-13', estimatedHours: 2, actualHours: 2.2 },
    ],
    assumptions: 'Mock data.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 8.8,
    deliveredAt: date('2026-09-27'),
    lesson: 'Calibração verificada no início da semana evita retrabalho.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: null,
  },
  {
    id: 'proposal-44',
    proposalDate: date('2026-09-22'),
    company: 'HidraTech Demo',
    requester: 'Camila Souza',
    email: 'camila.souza@example.com',
    phone: '(00) 90000-0044',
    service: 'Análise de falhas — lote TA mock 2',
    message: 'Terceiro caso mock de falhas TA.',
    totalValue: 850,
    totalHours: 6,
    quantity: 2,
    recordKind: 'batch',
    batchLabel: 'Mock falhas TA 02',
    serviceTypeId: 'vocab-8',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-13'],
    stages: [
      { serviceTypeId: 'vocab-8', label: 'Análise de falhas', resourceId: 'vocab-13', estimatedHours: 3, actualHours: 3.2 },
    ],
    assumptions: 'Mock catalog.',
    requestStatus: 'CONVERTED',
    recordStatus: 'COMPLETED',
    hasRecord: true,
    actualHours: 6.4,
    deliveredAt: date('2026-09-29'),
    lesson: 'Fratura em zona TA exige preparação metallográfica cuidadosa.',
    lessonStatus: 'FORMALIZED',
    deviationCauseId: 'vocab-25',
  },
  {
    id: 'proposal-45',
    proposalDate: date('2026-09-24'),
    company: 'ScanLab Demo',
    requester: 'Renata Pires',
    email: 'renata.pires@example.com',
    phone: '(00) 90000-0045',
    service: 'Scan + eng. reversa — lote TA em orçamento',
    message: 'Rascunho mock para testar assistente com histórico denso de casos TA.',
    totalValue: 4550,
    totalHours: 16,
    quantity: 2,
    recordKind: 'batch',
    batchLabel: 'Mock lote TA — orçamento aberto',
    serviceTypeId: 'vocab-1',
    partTraitIds: ['vocab-23'],
    resourceIds: ['vocab-14', 'vocab-19'],
    stages: [
      { serviceTypeId: 'vocab-1', label: 'Digitalização 3D', resourceId: 'vocab-14', estimatedHours: 5, actualHours: null },
      { serviceTypeId: 'vocab-2', label: 'Engenharia reversa', resourceId: 'vocab-19', estimatedHours: 3, actualHours: null },
    ],
    equipment: 'SCANNER DEMO + ZRE DEMO',
    assumptions: 'Registro mock em rascunho para demonstração do bloco A.',
    quoteMode: 'tariff',
    requestStatus: 'NEW',
    recordStatus: 'DRAFT',
    hasRecord: true,
  },
];
