import { QuoteRequest } from '@/app/(workspace)/solicitacoes/types';

export const SEED_REQUESTS: QuoteRequest[] = [
  {
    id: 'request-1',
    requestNumber: 'SO-2026-0001',
    requester: 'Hugo Oliveira',
    company: 'CARAMURU ALIMENTOS S.A.',
    email: 'hugooliveira@caramuru.com',
    phone: '+55 64 3404-0200',
    service: 'Digitalização 3D',
    message:
      'Realizar o escaneamento 3D e a engenharia reversa de lote de 34 componentes mecânicos pertencentes a equipamentos em uso ou em estoque na empresa Caramuru Alimentos.',
    receivedAt: '2026-09-18T08:42:00.000Z',
    status: 'NEW',
  },
  {
    id: 'request-2',
    requestNumber: 'SO-2026-0002',
    linkedRecordNumber: 'RS-2026-0002',
    linkedRecordId: 'record-2',
    requester: 'Humberto Dutra',
    company: 'BV8 COMERCIO VAREJO LTDA',
    email: 'bv8contato@gmail.com',
    phone: '+55 62 8141-7796',
    service: 'Digitalização 3D',
    message:
      'Gostaríamos de entender o prazo e as condições para digitalizar nossos componentes mecânicos.',
    receivedAt: '2026-09-17T15:10:00.000Z',
    status: 'ASSIGNED',
    assignedToUserId: 'demo-sebastiao',
    assignedToName: 'Sebastião',
  },
  {
    id: 'request-3',
    requestNumber: 'SO-2026-0003',
    linkedRecordNumber: 'RS-2026-0001',
    linkedRecordId: 'record-1',
    requester: 'Cleber Alves Ribeiro',
    company: 'VERTICAL SERVICOS E COMERCIO DE EQUIPAMENTOS LTDA',
    email: 'comercial@verticalserv.com',
    phone: '+55 62 3624-9325',
    service: 'Inspeção dimensional',
    message:
      'A solicitação foi aprovada comercialmente e já pode seguir para o registro do serviço. Realizar a avaliação dimensional de componentes para verificar sua conformidade com os requisitos normativos, desenhos técnicos e especificações aplicáveis, com a emissão de laudo técnico dimensional.',
    receivedAt: '2026-09-15T10:25:00.000Z',
    status: 'CONVERTED',
  },
  {
    id: 'request-4',
    requestNumber: 'SO-2026-0004',
    requester: 'Gabriel Badim Vilela',
    company: 'CBBR IMPORTS LTDA',
    email: 'rgbprint3d@gmail.com',
    phone: '+55 62 9438-8030',
    service: 'Engenharia Reversa',
    message: 'Pedido encerrado após retorno do cliente informando mudança de escopo.',
    receivedAt: '2026-09-12T09:05:00.000Z',
    status: 'ARCHIVED',
    archiveReason: 'Cliente informou mudança de escopo e encerrou o pedido antes da proposta.',
  },
  {
    id: 'request-5',
    requestNumber: 'SO-2026-0005',
    requester: 'Ricardo Mendes',
    company: 'INDUSTRIA GOIANA DE EIXOS LTDA',
    email: 'engenharia@igeixos.com.br',
    phone: '+55 62 3231-4400',
    service: 'Metrologia avançada ZEISS',
    message:
      'Solicitamos orçamento para inspeção dimensional de lote de 12 eixos usinados, com laudo comparativo ao desenho técnico revisão C. Peças já disponíveis para coleta no CD de Aparecida de Goiânia.',
    receivedAt: '2026-09-19T14:20:00.000Z',
    status: 'ASSIGNED',
    assignedToUserId: 'demo-joao',
    assignedToName: 'João',
    linkedRecordNumber: 'RS-2026-0005',
    linkedRecordId: 'record-5',
  },
  {
    id: 'request-6',
    requestNumber: 'SO-2026-0006',
    linkedRecordNumber: 'RS-2026-0006',
    linkedRecordId: 'record-6',
    requester: 'Patrícia Nogueira',
    company: 'USIMINAS MINEIRAS LTDA',
    email: 'patricia.nogueira@usiminas.com',
    phone: '+55 31 3614-7000',
    service: 'Tomografia industrial',
    message:
      'Inspeção interna não destrutiva de componente fundido com suspeita de porosidade. Cliente já aprovou proposta e aguarda laudo com imagens tomográficas.',
    receivedAt: '2026-09-08T11:15:00.000Z',
    status: 'CONVERTED',
  },
  {
    id: 'request-7',
    requestNumber: 'SO-2026-0007',
    requester: 'André Luiz Campos',
    company: 'MOINHO PH INDUSTRIA E COMERCIO LTDA',
    email: 'andre.campos@moinhoph.com.br',
    phone: '+55 62 3945-1180',
    service: 'Análise de falhas',
    message:
      'Rolamento de moinho apresentou trinca após 18 meses de operação. Precisamos de análise de causa raiz com inspeção dimensional e comparação ao projeto original.',
    receivedAt: '2026-09-20T09:00:00.000Z',
    status: 'NEW',
  },
  {
    id: 'request-8',
    requestNumber: 'SO-2026-0008',
    requester: 'Fernanda Costa',
    company: 'TECNOAR COMPRESSORES LTDA',
    email: 'fernanda.costa@tecnoar.com.br',
    phone: '+55 62 3098-2200',
    service: 'Nacionalização de componente',
    message:
      'Projeto de adaptação de conjunto importado para fabricação local. Cliente solicitou pausa após revisão interna do cronograma de P&D.',
    receivedAt: '2026-09-06T16:40:00.000Z',
    status: 'ARCHIVED',
    archiveReason: 'Projeto adiado pelo cliente para o próximo semestre fiscal.',
  },
  {
    id: 'request-9',
    requestNumber: 'SO-2026-0009',
    requester: 'Marcos Antônio Silva',
    company: 'AGROPECUARIA RIO VERDE LTDA',
    email: 'manutencao@agrorv.com.br',
    phone: '+55 64 3612-8800',
    service: 'Comparação CAD × peça física',
    message:
      'Precisamos validar desgaste em rotor de bomba após retrofit. Há desenho CAD disponível e a peça pode ser enviada ao laboratório na próxima semana.',
    receivedAt: '2026-09-21T10:30:00.000Z',
    status: 'NEW',
  },
];
