import type { VocabularyTerm } from '@/app/(workspace)/vocabulario/types';

import { applyMachineTariffsToVocabulary } from '../../machine-tariff';

import { MACHINE_TARIFF_SEED } from '../seed/machine-tariff-seed';

const RAW_VOCABULARY: VocabularyTerm[] = [
  {
    id: 'vocab-1',
    label: 'Digitalização de peças e impressão 3D',
    class: 'SERVICE_TYPE',
    guidance:
      'Captura da geometria, modelagem e fabricação aditiva para análise ou engenharia reversa.',
    active: true,
    updatedAt: '2026-09-14T09:00:00.000Z',
  },
  {
    id: 'vocab-2',
    label: 'Engenharia reversa e reconstrução de modelos CAD',
    class: 'SERVICE_TYPE',
    guidance: 'Reconstrução CAD a partir de digitalização e modelos técnicos.',
    active: true,
    updatedAt: '2026-09-08T09:00:00.000Z',
  },
  {
    id: 'vocab-3',
    label: 'Nacionalização e desenvolvimento de componentes',
    class: 'SERVICE_TYPE',
    guidance: 'Adaptação e desenvolvimento de componentes para o contexto nacional.',
    active: true,
    updatedAt: '2026-09-20T09:00:00.000Z',
  },
  {
    id: 'vocab-4',
    label: 'Metrologia avançada ZEISS e inspeção dimensional',
    class: 'SERVICE_TYPE',
    guidance:
      'Verificação de dimensões, tolerâncias e conformidade geométrica com equipamentos ZEISS.',
    active: true,
    updatedAt: '2026-09-15T09:00:00.000Z',
  },
  {
    id: 'vocab-5',
    label: 'Comparação entre modelo CAD e peça física',
    class: 'SERVICE_TYPE',
    guidance: 'Análise de conformidade entre modelo digital e peça medida.',
    active: true,
    updatedAt: '2026-09-20T09:00:00.000Z',
  },
  {
    id: 'vocab-6',
    label: 'Elaboração de mapas de desgaste',
    class: 'SERVICE_TYPE',
    guidance: 'Mapeamento e documentação de desgaste em componentes.',
    active: true,
    updatedAt: '2026-09-20T09:00:00.000Z',
  },
  {
    id: 'vocab-7',
    label: 'Tomografia industrial para inspeções internas não destrutivas',
    class: 'SERVICE_TYPE',
    guidance: 'Inspeção interna de peças sem destruição por tomografia.',
    active: true,
    updatedAt: '2026-09-20T09:00:00.000Z',
  },
  {
    id: 'vocab-8',
    label: 'Análise de falhas, quebras e anomalias',
    class: 'SERVICE_TYPE',
    guidance: 'Investigação técnica de falhas e anomalias em componentes.',
    active: true,
    updatedAt: '2026-09-20T09:00:00.000Z',
  },
  {
    id: 'vocab-9',
    label: 'Estruturação de árvores de equipamentos e identificação de peças críticas',
    class: 'SERVICE_TYPE',
    guidance: 'Organização de ativos e priorização de componentes críticos.',
    active: true,
    updatedAt: '2026-09-20T09:00:00.000Z',
  },
  {
    id: 'vocab-10',
    label: 'Criação de almoxarifado virtual e biblioteca digital de componentes',
    class: 'SERVICE_TYPE',
    guidance: 'Estruturação de biblioteca digital e almoxarifado virtual.',
    active: true,
    updatedAt: '2026-09-20T09:00:00.000Z',
  },
  {
    id: 'vocab-11',
    label: 'Elaboração de planos de manutenção e lubrificação',
    class: 'SERVICE_TYPE',
    guidance: 'Planos técnicos de manutenção e lubrificação de equipamentos.',
    active: true,
    updatedAt: '2026-09-20T09:00:00.000Z',
  },
  {
    id: 'vocab-12',
    label: 'Treinamentos técnicos',
    class: 'SERVICE_TYPE',
    guidance:
      'Capacitação em manutenção, metrologia, engenharia reversa, lubrificação e análise de falhas.',
    active: true,
    updatedAt: '2026-09-20T09:00:00.000Z',
  },
  {
    id: 'vocab-13',
    label: 'CMM PRISMO',
    class: 'RESOURCE',
    guidance: 'Recurso indicado para medições dimensionais com alta precisão.',
    active: true,
    updatedAt: '2026-09-08T09:00:00.000Z',
  },
  {
    id: 'vocab-14',
    label: 'ATOS Q',
    class: 'RESOURCE',
    guidance: 'Scanner óptico ATOS Q — tarifa da folha de custos.',
    active: true,
    updatedAt: '2026-09-07T09:00:00.000Z',
  },
  {
    id: 'vocab-15',
    label: 'BOSELLO MAX',
    class: 'RESOURCE',
    guidance: 'Tomógrafo industrial — tarifa da folha de custos.',
    active: true,
    updatedAt: '2026-09-06T09:00:00.000Z',
  },
  {
    id: 'vocab-16',
    label: 'CMM O-INSPECT',
    class: 'RESOURCE',
    guidance: 'MMC óptica ZEISS O-Inspect.',
    active: true,
    updatedAt: '2026-09-07T09:00:00.000Z',
  },
  {
    id: 'vocab-17',
    label: 'CMM CONTURA',
    class: 'RESOURCE',
    guidance: 'MMC ZEISS CONTURA.',
    active: true,
    updatedAt: '2026-09-07T09:00:00.000Z',
  },
  {
    id: 'vocab-18',
    label: 'T-SCAN Hawk 2',
    class: 'RESOURCE',
    guidance: 'Scanner portátil T-SCAN Hawk 2.',
    active: true,
    updatedAt: '2026-09-07T09:00:00.000Z',
  },
  {
    id: 'vocab-19',
    label: 'CMM DuraMax',
    class: 'RESOURCE',
    guidance: 'MMC portátil ZEISS DuraMax — folha de custos.',
    active: true,
    updatedAt: '2026-06-20T09:00:00.000Z',
  },
  {
    id: 'vocab-20',
    label: 'ZEISS ZRE',
    class: 'RESOURCE',
    guidance: 'ZEISS Reverse Engineering — licença e posto de trabalho; tarifa da folha de custos.',
    active: true,
    updatedAt: '2026-09-18T09:00:00.000Z',
  },
  {
    id: 'vocab-21',
    label: 'Bambu Lab A1',
    class: 'RESOURCE',
    guidance: 'Impressora 3D para protótipos em engenharia reversa.',
    active: true,
    updatedAt: '2026-09-21T09:00:00.000Z',
    hourlyRate: 42,
  },
  {
    id: 'vocab-22',
    label: 'Superfície livre',
    class: 'PART_TRAIT',
    guidance: 'Região sem uma definição geométrica simples, comum em peças moldadas.',
    active: true,
    updatedAt: '2026-09-12T09:00:00.000Z',
  },
  {
    id: 'vocab-23',
    label: 'Tolerância apertada',
    class: 'PART_TRAIT',
    guidance: 'Característica que exige controle dimensional mais rigoroso.',
    active: true,
    updatedAt: '2026-09-10T09:00:00.000Z',
  },
  {
    id: 'vocab-24',
    label: 'Acesso incompleto à região',
    class: 'DEVIATION_CAUSE',
    guidance: 'Registrar quando a geometria não pode ser medida por falta de acesso.',
    active: true,
    updatedAt: '2026-09-06T09:00:00.000Z',
  },
  {
    id: 'vocab-25',
    label: 'Fixação mais complexa que o previsto',
    class: 'DEVIATION_CAUSE',
    guidance: 'Tempo extra para preparar dispositivo ou acessar a região.',
    active: true,
    updatedAt: '2026-09-10T09:00:00.000Z',
  },
  {
    id: 'vocab-26',
    label: 'Programação subestimada',
    class: 'DEVIATION_CAUSE',
    guidance: 'Rotina de medição ou digitalização levou mais tempo que o estimado.',
    active: true,
    updatedAt: '2026-09-09T09:00:00.000Z',
  },
];

export const SEED_VOCABULARY = applyMachineTariffsToVocabulary(RAW_VOCABULARY, MACHINE_TARIFF_SEED);
